// @isTest 
// public with sharing class QuoteTriggerHandlerTest {

//     @isTest static void updateWatermarkTest() {
//         //create a primary quote associated with the opportunity and different values
//         SBQQ__Quote__c primaryQuote = new SBQQ__Quote__c();
//         primaryQuote.SBQQ__Primary__c = True;
//         primaryQuote.Id = testOpp.SBQQ__PrimaryQuote__c;
//         primaryQuote.SBQQ__ShippingCountry__c = 'USA';
//         primaryQuote.SBQQ__ShippingCity__c = 'Madison';
//         primaryQuote.SBQQ__ShippingPostalCode__c = '55555';
//         primaryQuote.SBQQ__ShippingState__c = 'Wisconsin';
//         primaryQuote.SBQQ__ShippingStreet__c = 'Phillips';
//         primaryQuote.SBQQ__BillingCity__c = 'Bozeman';
//         primaryQuote.SBQQ__BillingCountry__c = 'USA';
//         primaryQuote.SBQQ__BillingPostalCode__c = '66666';
//         primaryQuote.SBQQ__BillingState__c = 'Main';
//         primaryQuote.SBQQ__BillingStreet__c = 'Perth';

//         insert primaryQuote;
//         System.debug('inserted test Quote -----> ' + primaryQuote);
//     }
// }
